/* Generated by Cython 0.29.28 */

#ifndef __PYX_HAVE__poker__game_state
#define __PYX_HAVE__poker__game_state

#include "Python.h"

#ifndef __PYX_HAVE_API__poker__game_state

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *__pyx_f_5poker_10game_state_create_deck(int __pyx_skip_dispatch);

__PYX_EXTERN_C PyObject *SUITS;
__PYX_EXTERN_C PyObject *VALUES;

#endif /* !__PYX_HAVE_API__poker__game_state */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initgame_state(void);
#else
PyMODINIT_FUNC PyInit_game_state(void);
#endif

#endif /* !__PYX_HAVE__poker__game_state */
