/* Generated by Cython 0.29.28 */

#ifndef __PYX_HAVE__poker__poker_game
#define __PYX_HAVE__poker__poker_game

#include "Python.h"

#ifndef __PYX_HAVE_API__poker__poker_game

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *SUITS;
__PYX_EXTERN_C PyObject *VALUES;

#endif /* !__PYX_HAVE_API__poker__poker_game */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpoker_game(void);
#else
PyMODINIT_FUNC PyInit_poker_game(void);
#endif

#endif /* !__PYX_HAVE__poker__poker_game */
